experiment

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -1,5 +1,6 @@
 name: experiments
 on:
+  push:
   workflow_dispatch:
 jobs:
   config:
@@ -28,6 +29,6 @@ jobs:
       - name: run tests
         shell: bash
         run: |
-          echo ${{ needs.config.outputs.config }} | jq '.'
-          echo fromJSON="${{ fromJSON(needs.config.outputs.config) }}" || echo "config failed"
-          echo fromJSON="${{ fromJSON(needs.config.outputs.config.fmt.disabled) }}" || echo "fmt disabled"
+          echo '${{ needs.config.outputs.config }}' | jq '.'
+          echo fromJSON="{{ fromJSON(needs.config.outputs.config) }}" || echo "config failed"
+          echo fromJSON="{{ fromJSON(needs.config.outputs.config.fmt.disabled) }}" || echo "fmt disabled"
